**Theoretical Questions**

Q1 Explain the purpose and advantages of Numpy in scientific computing and data analysis. How does it
enhance python's capabilities for numerical operations?

ANS) Numpy (Numerical python) is a fundamental library for scientific computing and data analysis in python. Here are some key purposes and advantages of using Numpy:

purpose of Numpy

1) Efficient Array Computations: Numpy provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

2)Foundation for Other Libraries: Many other scientific computing and data analysis libraries, such as pandas, Scipy, and Matplotlib, are built on top of Numpy, making it a cornerstone of the scientific python ecosystem.

Advantages of Numpy

1) performance: Numpy is highly optimized for numerical operations. It uses pre-compiled C code, which makes array operations significantly faster than using python lists.

2) Memory Efficiency: Numpy arrays consume less memory compared to python lists, which is crucial when working with large datasets.

3)Vectorization: Numpy allows for vectorized operations, which means you can perform element-wise operations on arrays without the need for explicit loops. This not only makes the code more readable but also enhances performance.

4)Broadcasting: This feature allows Numpy to handle arithmetic operations on arrays of different shapes in a flexible way, making it easier to write efficient code.

5)Integration with Other Libraries: Numpy seamlessly integrates with other libraries used for data analysis and scientific computing, such as pandas for data manipulation, Scipy for advanced mathematical functions, and Matplotlib for plotting

Enhancing python’s Capabilities

1) Numerical Operations: Numpy enhances python’s capabilities by providing a powerful N-dimensional array object, which supports a wide range of mathematical operations, including linear algebra, Fourier transforms, and random number generation.

2)Data Manipulation: With its array manipulation capabilities, Numpy makes it easier to clean, transform, and aggregate data, which is essential for data analysis.


In summary, Numpy’s ability to handle extensive datasets, execute complex mathematical operations, and integrate with various scientific computing tools makes it an indispensable asset for researchers, data scientists, engineers, and analysts

Q2  Compare and contrast np.mean() and np.average() functions in Numpy. When would you use one over the
other?

ANS) Both np.mean() and np.average() functions in Numpy are used to calculate the average of an array, but they have some differences in functionality and use cases.

np.mean()

- purpose: Calculates the arithmetic mean (average) of the elements in an array.

- Syntax: np.mean(arr, axis=None)

- Weights: Does not support weights; all elements are considered equally.

- Use Case: Use np.mean() when you need a simple arithmetic mean without considering any weights.

np.average()

- purpose: Calculates the weighted average of the elements in an array.

-Syntax: np.average(arr, axis=None, weights=None)

- Weights: Supports weights; you can pass an array of weights to compute a weighted average.

- Use Case: Use np.average() when you need to calculate a weighted average, where different elements contribute differently to the final average.

Example
Here’s a quick example to illustrate the difference:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])

# Using np.mean()
mean_value = np.mean(arr)
print("Mean:", mean_value)

average_value = np.average(arr)
print("Average without weights:", average_value)

# Using np.average() with weights
weighted_average_value = np.average(arr, weights=weights)
print("Weighted Average:", weighted_average_value)

Mean: 3.0
Average without weights: 3.0
Weighted Average: 3.6666666666666665


When to Use Which

- Use np.mean(): When you need a straightforward arithmetic mean and do not need to consider different weights for the elements.

- Use np.average(): When you need to calculate a weighted average, where some elements have more significance than others.

- In summary, while both functions can calculate the arithmetic mean, np.average() provides additional flexibility with its ability to handle weights

Q3
Describe the methods for reversing a Numpy array along different axes. provide examples for 1D and 2D
arrays?

ANS) Reversing a Numpy array along different axes can be done using several methods.
1. Using np.flip()
The np.flip() function reverses the order of elements in an array along the specified axis.

Example for 1D Array:

In [ ]:
import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
reversed_1d = np.flip(arr_1d)

print("Original 1D array:", arr_1d)
print("Reversed 1D array:", reversed_1d)

Original 1D array: [1 2 3 4 5]
Reversed 1D array: [5 4 3 2 1]


In [ ]:
#Example for 2D Array:
import numpy as np

# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = np.flip(arr_2d, axis=0)  # Reverse along rows
reversed_cols = np.flip(arr_2d, axis=1)  # Reverse along columns

print("Original 2D array:\n", arr_2d)
print("Reversed along rows:\n", reversed_rows)
print("Reversed along columns:\n", reversed_cols)

Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed along rows:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed along columns:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


2. Using Array Slicing
Array slicing can also be used to reverse arrays.

Example for 1D Array:

In [ ]:
import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
reversed_1d = arr_1d[::-1]

print("Original 1D array:", arr_1d)
print("Reversed 1D array:", reversed_1d)

Original 1D array: [1 2 3 4 5]
Reversed 1D array: [5 4 3 2 1]


In [ ]:
#Example for 2D Array:
import numpy as np

# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = arr_2d[::-1, :]  # Reverse along rows
reversed_cols = arr_2d[:, ::-1]  # Reverse along columns

print("Original 2D array:\n", arr_2d)
print("Reversed along rows:\n", reversed_rows)
print("Reversed along columns:\n", reversed_cols)

Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed along rows:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed along columns:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


Q4  How can you determine the data type of elements in a Numpy array? Discuss the importance of data types
in memory management and performance.

ANS) To determine the data type of elements in a Numpy array, you can use the dtype attribute. This attribute provides information about the type of elements stored in the array.

Example:

In [ ]:
import numpy as np

# Creating a Numpy array
arr = np.array([1, 2, 3, 4, 5])

# Checking the data type of the array elements
print("Data type of array elements:", arr.dtype)

Data type of array elements: int64


Importance of Data Types in Memory Management and performance

1) Memory Efficiency:
- Memory Allocation: Different data types require different amounts of memory. For example, an int32 type uses 4 bytes, while an int64 type uses 8 bytes. Choosing the appropriate data type can save memory, especially when dealing with large datasets.

- Compact Storage: Using the smallest possible data type that can accurately represent your data helps in reducing the overall memory footprint

2) performance:

- Speed of Operations: Operations on smaller data types are generally faster because they require less memory bandwidth and can be processed more quickly by the CpU.
- Vectorized Operations: Numpy is optimized for vectorized operations, which means it can perform operations on entire arrays at once. The efficiency of these operations can be significantly affected by the data type of the array elements

3) Data Integrity:

- Type Safety: Ensuring that data is stored in the correct type helps prevent errors. For example, storing a floating-point number in an integer array can lead to loss of precision.

- Consistency: Using consistent data types across arrays ensures that operations between arrays are performed correctly and efficiently.

4) Interoperability:

- Compatibility with Other Libraries: Many scientific computing libraries expect data in specific formats. Using the correct data types ensures compatibility and efficient data exchange between libraries.

- Understanding and choosing the right data types is crucial for optimizing both memory usage and computational performance in your applications

Q5 Define ndarrays in Numpy and explain their key features. How do they differ from standard python lists?

ANS) Numpy is a powerful library in python used for numerical computations. At its core is the ndarray (N-dimensional array), which is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.

**Key Features of ndarray:**

1) Multi-Dimensional Arrays: ndarray supports arrays of arbitrary dimensions, making it ideal for handling large datasets, images, and other types of numerical data.

2) Homogeneous Data: All elements in an ndarray must be of the same data type, ensuring efficient memory usage and performance.

3) Fixed Size: Once created, the size of an ndarray cannot be changed. Any resizing operation will create a new array.

4) Vectorized Operations: Numpy allows for element-wise operations on arrays without the need for explicit loops, making computations faster and more concise.

5) Broadcasting: This feature allows Numpy to perform operations on arrays of different shapes by automatically expanding their dimensions to match each other.

6) Advanced Indexing and Slicing: Numpy provides powerful tools for accessing and manipulating array elements.

**Differences from Standard python Lists:**

1) Performance: ndarray operations are generally faster than equivalent operations on python lists due to optimized C implementations and contiguous memory storage.

2) Memory Efficiency: ndarray uses less memory compared to lists because it stores elements of the same type in a contiguous block of memory.

3) Fixed Size: Unlike lists, which can grow dynamically, ndarray has a fixed size. Changing the size of an ndarray creates a new array.

4) Homogeneous Elements: All elements in an ndarray must be of the same type, whereas lists can contain elements of different types.

5) Vectorized Operations: Numpy supports vectorized operations, allowing for efficient and concise mathematical computations, which is not possible with standard lists.

Here’s a simple example to illustrate some of these features:

In [ ]:
import numpy as np

# Creating a 2D ndarray
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Accessing elements
print(arr[0, 0])

# Broadcasting example
arr2 = np.array([1, 2, 3])
result = arr + arr2
print(result)

1
[[2 4 6]
 [5 7 9]]


Q6  Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations?

ANS) NumPy arrays offer significant performance benefits over Python lists, especially for large-scale numerical operations. Here are some key reasons why:

1. Memory Efficiency

- Contiguous Memory Allocation: NumPy arrays store elements in contiguous memory blocks, which reduces memory overhead and improves cache performance.

- Homogeneous Data: All elements in a NumPy array are of the same type, which allows for more efficient memory usage compared to Python lists that can store elements of different types.

2. Speed
- Vectorized Operations: NumPy supports vectorized operations, which means operations are applied to entire arrays at once without the need for explicit loops. This is much faster than iterating through elements in a Python list.

- Optimized C Implementation: NumPy operations are implemented in C, which is a lower-level and faster language than Python. This results in significant speed improvements for numerical computations.

3. Broadcasting
- Automatic Dimension Expansion: NumPy’s broadcasting feature allows it to perform operations on arrays of different shapes by automatically expanding their dimensions to match each other. This eliminates the need for manual resizing and looping.

4. Advanced Mathematical Functions
- Rich Functionality: NumPy provides a wide range of mathematical and statistical functions that are optimized for performance. These functions are not available in standard Python lists.

**Performance Comparison Example**

Here’s a simple example to illustrate the performance difference between NumPy arrays and Python lists:

In [ ]:
import numpy as np
import time

# Creating large arrays and lists
size = 1000000
list1 = list(range(size))
list2 = list(range(size))
array1 = np.arange(size)
array2 = np.arange(size)

# Timing list addition
start_time = time.time()
result_list = [x + y for x, y in zip(list1, list2)]
print("List addition took:", time.time() - start_time, "seconds")

# Timing NumPy array addition
start_time = time.time()
result_array = array1 + array2
print("NumPy array addition took:", time.time() - start_time, "seconds")

List addition took: 0.2373485565185547 seconds
NumPy array addition took: 0.00761103630065918 seconds


- In this example, you’ll typically find that the NumPy array addition is significantly faster than the list addition due to the reasons mentioned above.

Q7  Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output?

ANS) The vstack() and hstack() functions in NumPy are used to stack arrays in different orientations. Here’s a comparison of the two:

**vstack()**

- Purpose: Stacks arrays in sequence vertically (row-wise).

- Axis: Equivalent to concatenation along the first axis (axis=0).

- Usage: Useful for adding rows to an array.

**hstack()**

- Purpose: Stacks arrays in sequence horizontally (column-wise).

- Axis: Equivalent to concatenation along the second axis (axis=1).

- Usage: Useful for adding columns to an array.


**Examples**

**vstack()**

In [ ]:
import numpy as np

# Creating two 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stacking them vertically
result_vstack = np.vstack((a, b))
print(result_vstack)

[[1 2 3]
 [4 5 6]]


In [ ]:
#hstack()
import numpy as np

# Creating two 2D arrays
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

# Stacking them horizontally
result_hstack = np.hstack((a, b))
print(result_hstack)

[[1 4]
 [2 5]
 [3 6]]


**Key Differences**

- Orientation: vstack() stacks arrays vertically, adding rows, while hstack() stacks arrays horizontally, adding columns.

- Axis: vstack() operates along the first axis (axis=0), whereas hstack() operates along the second axis (axis=1).

Q8 . Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions?

ANS. The fliplr() and flipud() functions in NumPy are used to flip arrays, but they do so in different directions. Here’s a detailed comparison:

**fliplr()**

- Purpose: Flips the array in the left/right direction (horizontally).

- Axis: Operates along the second axis (axis=1).

- Effect: Reverses the order of columns while preserving the rows.

**flipud()**

- Purpose: Flips the array in the up/down direction (vertically).

- Axis: Operates along the first axis (axis=0).

- Effect: Reverses the order of rows while preserving the columns.

**Examples**

fliplr()


In [ ]:
import numpy as np

# Creating a 2D array
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Flipping the array horizontally
result_fliplr = np.fliplr(a)
print(result_fliplr)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


- In this example, the columns of the array are reversed.

In [ ]:
import numpy as np

# Creating a 2D array
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Flipping the array vertically
result_flipud = np.flipud(a)
print(result_flipud)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


- In this example, the rows of the array are reversed.

**Key Differences**

- Direction of Flip: fliplr() flips the array horizontally (left to right), while flipud() flips it vertically (up to down).

- Axis of Operation: fliplr() operates along axis=1, whereas flipud() operates along axis=0.

**These functions are particularly useful for image processing, data manipulation, and other applications where the orientation of data matters.**

Q9 Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

ANS. The array_split() method in NumPy is used to split an array into multiple sub-arrays. It is particularly useful when you need to split an array into sections that may not be of equal size.

**Functionality**

- Syntax: numpy.array_split(ary, indices_or_sections, axis=0)

- ary: The input array to be split.

- indices_or_sections: If an integer, it indicates the number of equal or nearly equal sub-arrays to create. If a 1-D array of sorted integers, it specifies the indices at which to split.

- axis: The axis along which to split the array. Default is 0.

**Handling Uneven Splits**
When the array cannot be evenly divided by the specified number of splits, array_split() ensures that the resulting sub-arrays are as equal in size as possible. It does this by distributing the remainder elements across the sub-arrays.

- For example, if you have an array of length 9 and you want to split it into 4 parts, array_split() will create sub-arrays of sizes 3, 2, 2, and 2.

**Examples**

Example 1: Splitting into Equal Parts

In [ ]:
import numpy as np

# Creating an array
arr = np.arange(8)

# Splitting into 3 parts
result = np.array_split(arr, 3)
print(result)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]


Example 2: Handling Uneven Splits

In [ ]:
import numpy as np

# Creating an array
arr = np.arange(9)

# Splitting into 4 parts
result = np.array_split(arr, 4)
print(result)

[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In this example, the array of length 9 is split into 4 parts, with the sizes of the sub-arrays being as equal as possible.

Q10 Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?


ANS. **Vectorization**

Vectorization in NumPy refers to the process of performing operations on entire arrays without the need for explicit loops. This is achieved by applying operations element-wise across arrays, leveraging low-level optimizations in C and Fortran.

**Benefits:**

1. Speed: Vectorized operations are significantly faster than equivalent operations using Python loops because they are executed in compiled code.

2. Readability: Code that uses vectorized operations is often more concise and easier to read.

3. Efficiency: Vectorization reduces the overhead of Python’s interpreted loops, leading to more efficient use of CPU resources.

**Example of Vectorization:**

In [ ]:
import numpy as np

# Creating two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vectorized addition
result = a + b
print(result)

[5 7 9]


**Broadcasting**

Broadcasting describes how NumPy handles arrays with different shapes during arithmetic operations. It allows NumPy to perform element-wise operations on arrays of different shapes by automatically expanding their dimensions to match each other.


**Rules of Broadcasting:**

1. Trailing Dimensions: NumPy compares arrays element-wise starting from the trailing dimensions.

2. Dimension Compatibility: Two dimensions are compatible if they are equal or if one of them is 1.

3. Expansion: If one array has fewer dimensions, it is expanded by adding new axes of size 1 at the beginning.

**Example of Broadcasting:**

In [ ]:
import numpy as np

# Creating a 2D array and a 1D array
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])

# Broadcasting addition
result = a + b
print(result)

[[2 4 6]
 [5 7 9]]


In this example, the 1D array b is broadcasted to match the shape of the 2D array a

**Contribution to Efficient Array Operations:**

1. Reduced Memory Usage: Broadcasting avoids the need to create large intermediate arrays, saving memory.

2. Faster Computations: Both vectorization and broadcasting allow operations to be executed in compiled code, which is much faster than interpreted Python code.

3. Simplified Code: These techniques lead to more concise and readable code, reducing the likelihood of errors.

**PRACTICAL QUESTIONS**

Q1 Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns?

In [ ]:
import numpy as np

# Creating a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))
print("Original array:\n", array)

# Interchanging rows and columns (transposing the array)
transposed_array = np.transpose(array)
print("Transposed array:\n", transposed_array)

Original array:
 [[ 1 54 90]
 [79 60 20]
 [53 90 21]]
Transposed array:
 [[ 1 79 53]
 [54 60 90]
 [90 20 21]]


Q2  Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array?

In [ ]:
import numpy as np

# Creating a 1D array with 10 elements
array_1d = np.arange(10)
print("Original 1D array:\n", array_1d)

# Reshaping into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("Reshaped into 2x5 array:\n", array_2x5)

# Reshaping into a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)
print("Reshaped into 5x2 array:\n", array_5x2)

Original 1D array:
 [0 1 2 3 4 5 6 7 8 9]
Reshaped into 2x5 array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Reshaped into 5x2 array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Q3 Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array?

In [ ]:
import numpy as np

# Creating a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)
print("Original 4x4 array:\n", array_4x4)

# Adding a border of zeros to create a 6x6 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("6x6 array with border of zeros:\n", array_6x6)

Original 4x4 array:
 [[0.98468416 0.01953426 0.16436709 0.1012348 ]
 [0.09786272 0.7944711  0.98305087 0.91895122]
 [0.35855258 0.57345487 0.91021819 0.41573982]
 [0.67749053 0.87495456 0.41178658 0.65752078]]
6x6 array with border of zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.98468416 0.01953426 0.16436709 0.1012348  0.        ]
 [0.         0.09786272 0.7944711  0.98305087 0.91895122 0.        ]
 [0.         0.35855258 0.57345487 0.91021819 0.41573982 0.        ]
 [0.         0.67749053 0.87495456 0.41178658 0.65752078 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Q4 Using NumPy, create an array of integers from 10 to 60 with a step of 5?

In [ ]:
import numpy as np

# Creating the array
array = np.arange(10, 65, 5)
print("Array:", array)

Array: [10 15 20 25 30 35 40 45 50 55 60]


Q5  Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element ?

In [ ]:
import numpy as np

# Creating a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Applying uppercase transformation
uppercase_array = np.char.upper(array)
print("Uppercase:\n", uppercase_array)

# Applying lowercase transformation
lowercase_array = np.char.lower(array)
print("Lowercase:\n", lowercase_array)

# Applying title case transformation
titlecase_array = np.char.title(array)
print("Title case:\n", titlecase_array)

Uppercase:
 ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase:
 ['python' 'numpy' 'pandas']
Title case:
 ['Python' 'Numpy' 'Pandas']


Q6 Generate a NumPy array of words. Insert a space between each character of every word in the array?

In [ ]:
import numpy as np

# Creating a NumPy array of words
words = np.array(['python', 'numpy', 'pandas'])

# Inserting a space between each character of every word
spaced_words = np.char.join(" ", words)
print("Original words:\n", words)
print("Words with spaces between characters:\n", spaced_words)

Original words:
 ['python' 'numpy' 'pandas']
Words with spaces between characters:
 ['p y t h o n' 'n u m p y' 'p a n d a s']


Q7  Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division?

In [ ]:
import numpy as np

# Creating two 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Element-wise addition
addition = np.add(array1, array2)
print("Element-wise addition:\n", addition)

# Element-wise subtraction
subtraction = np.subtract(array1, array2)
print("Element-wise subtraction:\n", subtraction)

# Element-wise multiplication
multiplication = np.multiply(array1, array2)
print("Element-wise multiplication:\n", multiplication)

# Element-wise division
division = np.divide(array1, array2)
print("Element-wise division:\n", division)

Element-wise addition:
 [[ 8 10 12]
 [14 16 18]]
Element-wise subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Element-wise multiplication:
 [[ 7 16 27]
 [40 55 72]]
Element-wise division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


Q8  Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements?

In [ ]:
import numpy as np

# Creating a 5x5 identity matrix
identity_matrix = np.identity(5)
print("5x5 Identity Matrix:\n", identity_matrix)

# Extracting the diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("Diagonal Elements:\n", diagonal_elements)

5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements:
 [1. 1. 1. 1. 1.]


Q9  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array?

In [ ]:
import numpy as np

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Generating a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)
print("Random Array:\n", random_array)

# Finding all prime numbers in the array
prime_numbers = [num for num in random_array if is_prime(num)]
print("Prime Numbers:\n", prime_numbers)

Random Array:
 [913 820  64 299 367 380 553 885  89 130 910 986  29 417 388 491 215 543
 285 335 100 359  25 454 388 232 707 435 290 228 792 389 706 203  35 288
 956 951 245 581 670 195 555 271 387 547  36 810 828 528 698 574 231 822
 704 160 212 883 986 229 614 183  98 217 800 766 542 315  89 713 494 879
  31 454 909 417 429 233 995 413 246 676 800 294 502 475 514 436 410  27
 194 745 252 317 940 782 949 889 610 290]
Prime Numbers:
 [367, 89, 29, 491, 359, 389, 271, 547, 883, 229, 89, 31, 233, 317]


Q10  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages?

In [ ]:
import numpy as np

# Generating a NumPy array of daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(20, 40, size=30)  # Random temperatures between 20 and 40 degrees
print("Daily Temperatures:\n", daily_temperatures)

# Reshaping the array to represent weeks (4 weeks, 7 days each, plus 2 extra days)
weeks = daily_temperatures[:28].reshape(4, 7)
extra_days = daily_temperatures[28:]

# Calculating weekly averages
weekly_averages = np.mean(weeks, axis=1)
print("Weekly Averages:\n", weekly_averages)

# Handling the extra days (if any)
if extra_days.size > 0:
    extra_days_average = np.mean(extra_days)
    print("Average of extra days:\n", extra_days_average)

Daily Temperatures:
 [29 36 37 30 21 21 22 34 23 21 24 25 20 28 39 29 34 24 23 36 35 36 35 29
 32 23 28 25 38 35]
Weekly Averages:
 [28.         25.         31.42857143 29.71428571]
Average of extra days:
 36.5
